# Generated by Django 5.2.7 on 2025-10-09 14:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('code_hex', models.CharField(blank=True, help_text='Ex: #FF5733', max_length=7, verbose_name='Code couleur (hex)')),
            ],
            options={
                'verbose_name': 'Couleur',
                'verbose_name_plural': 'Couleurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Taille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10, unique=True, verbose_name='Nom')),
                ('type_taille', models.CharField(choices=[('standard', 'Standard (XS, S, M, L, XL, XXL)'), ('numerique', 'Numérique (36, 38, 40, 42, etc.)'), ('autre', 'Autre')], default='standard', max_length=20, verbose_name='Type de taille')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Taille',
                'verbose_name_plural': 'Tailles',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Vetement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('reference', models.CharField(help_text='Code unique du vêtement', max_length=50, unique=True, verbose_name='Référence')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('genre', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme'), ('unisexe', 'Unisexe'), ('enfant', 'Enfant')], max_length=20, verbose_name='Genre')),
                ('saison', models.CharField(choices=[('printemps', 'Printemps'), ('ete', 'Été'), ('automne', 'Automne'), ('hiver', 'Hiver'), ('toute_saison', 'Toute saison')], default='toute_saison', max_length=20, verbose_name='Saison')),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Prix d'achat")),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix de vente')),
                ('quantite_stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité en stock')),
                ('stock_minimum', models.IntegerField(default=5, help_text='Alerte si stock inférieur', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock minimum')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vetements/', verbose_name='Image')),
                ('marque', models.CharField(blank=True, max_length=100, verbose_name='Marque')),
                ('matiere', models.CharField(blank=True, help_text='Ex: Coton 100%, Polyester 60%, etc.', max_length=200, verbose_name='Matière')),
                ('actif', models.BooleanField(default=True, help_text='Vêtement disponible à la vente', verbose_name='Actif')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vetements', to='vetements.categorie', verbose_name='Catégorie')),
                ('couleurs', models.ManyToManyField(related_name='vetements', to='vetements.couleur', verbose_name='Couleurs disponibles')),
                ('tailles', models.ManyToManyField(related_name='vetements', to='vetements.taille', verbose_name='Tailles disponibles')),
            ],
            options={
                'verbose_name': 'Vêtement',
                'verbose_name_plural': 'Vêtements',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
