# Generated by Django 5.2.7 on 2025-10-09 14:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vetement',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='vetement',
            name='couleurs',
        ),
        migrations.RemoveField(
            model_name='vetement',
            name='prix_vente',
        ),
        migrations.RemoveField(
            model_name='vetement',
            name='quantite_stock',
        ),
        migrations.RemoveField(
            model_name='vetement',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='vetement',
            name='stock_minimum',
        ),
        migrations.RemoveField(
            model_name='vetement',
            name='tailles',
        ),
        migrations.AddField(
            model_name='vetement',
            name='a_laver',
            field=models.BooleanField(default=False, verbose_name='À laver'),
        ),
        migrations.AddField(
            model_name='vetement',
            name='a_repasser',
            field=models.BooleanField(default=False, verbose_name='À repasser'),
        ),
        migrations.AddField(
            model_name='vetement',
            name='couleur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vetements', to='vetements.couleur', verbose_name='Couleur principale'),
        ),
        migrations.AddField(
            model_name='vetement',
            name='date_achat',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'achat"),
        ),
        migrations.AddField(
            model_name='vetement',
            name='derniere_utilisation',
            field=models.DateField(blank=True, null=True, verbose_name='Dernière fois porté'),
        ),
        migrations.AddField(
            model_name='vetement',
            name='emplacement',
            field=models.CharField(blank=True, help_text='Ex: Armoire chambre, Penderie entrée', max_length=100, verbose_name='Emplacement'),
        ),
        migrations.AddField(
            model_name='vetement',
            name='etat',
            field=models.CharField(choices=[('neuf', 'Neuf'), ('excellent', 'Excellent état'), ('bon', 'Bon état'), ('usage', "État d'usage"), ('reparer', 'À réparer')], default='bon', max_length=20, verbose_name='État'),
        ),
        migrations.AddField(
            model_name='vetement',
            name='favori',
            field=models.BooleanField(default=False, help_text='Vêtement que vous portez souvent', verbose_name='Favori'),
        ),
        migrations.AddField(
            model_name='vetement',
            name='lieu_achat',
            field=models.CharField(blank=True, help_text='Ex: Zara, en ligne, marché...', max_length=200, verbose_name="Lieu d'achat"),
        ),
        migrations.AddField(
            model_name='vetement',
            name='nombre_portage',
            field=models.IntegerField(default=0, verbose_name='Nombre de fois porté'),
        ),
        migrations.AddField(
            model_name='vetement',
            name='notes',
            field=models.TextField(blank=True, help_text="Notes personnelles, taille réelle, conseils d'entretien...", verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='vetement',
            name='prete',
            field=models.BooleanField(default=False, help_text='Cochez si vous avez prêté ce vêtement', verbose_name='Prêté'),
        ),
        migrations.AddField(
            model_name='vetement',
            name='prete_a',
            field=models.CharField(blank=True, max_length=100, verbose_name='Prêté à'),
        ),
        migrations.AddField(
            model_name='vetement',
            name='taille',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vetements', to='vetements.taille', verbose_name='Taille'),
        ),
        migrations.AlterField(
            model_name='vetement',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout à la garde-robe"),
        ),
        migrations.AlterField(
            model_name='vetement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vetements/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='vetement',
            name='nom',
            field=models.CharField(help_text='Ex: T-shirt bleu Nike', max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='vetement',
            name='prix_achat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optionnel', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Prix d'achat (€)"),
        ),
        migrations.CreateModel(
            name='Tenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Bureau casual, Soirée été', max_length=200, verbose_name='Nom de la tenue')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('occasion', models.CharField(choices=[('travail', 'Travail'), ('sport', 'Sport'), ('soiree', 'Soirée'), ('decontracte', 'Décontracté'), ('ceremonie', 'Cérémonie'), ('autre', 'Autre')], default='decontracte', max_length=20, verbose_name='Occasion')),
                ('saison', models.CharField(choices=[('printemps', 'Printemps'), ('ete', 'Été'), ('automne', 'Automne'), ('hiver', 'Hiver'), ('toute_saison', 'Toute saison')], default='toute_saison', max_length=20, verbose_name='Saison')),
                ('favori', models.BooleanField(default=False, verbose_name='Tenue favorite')),
                ('nombre_fois_portee', models.IntegerField(default=0, verbose_name='Nombre de fois portée')),
                ('derniere_fois_portee', models.DateField(blank=True, null=True, verbose_name='Dernière fois portée')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tenues/', verbose_name='Photo de la tenue')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('vetements', models.ManyToManyField(related_name='tenues', to='vetements.vetement', verbose_name='Vêtements')),
            ],
            options={
                'verbose_name': 'Tenue',
                'verbose_name_plural': 'Tenues',
                'ordering': ['-date_creation'],
            },
        ),
    ]
