# Generated by Django 5.2.7 on 2025-10-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetements', '0002_remove_vetement_actif_remove_vetement_couleurs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Barcelone Juillet 2025, Weekend Normandie', max_length=200, verbose_name='Nom du voyage')),
                ('destination', models.CharField(max_length=200, verbose_name='Destination')),
                ('type_voyage', models.CharField(choices=[('weekend', 'Weekend (1-3 jours)'), ('semaine', 'Semaine (4-7 jours)'), ('long', 'Long séjour (8+ jours)'), ('professionnel', 'Voyage professionnel'), ('vacances', 'Vacances')], max_length=20, verbose_name='Type de voyage')),
                ('date_depart', models.DateField(verbose_name='Date de départ')),
                ('date_retour', models.DateField(verbose_name='Date de retour')),
                ('meteo_prevue', models.CharField(blank=True, help_text='Ex: Ensoleillé 25°C, Pluvieux 15°C', max_length=200, verbose_name='Météo prévue')),
                ('climat', models.CharField(blank=True, help_text='Ex: Chaud, Froid, Tempéré', max_length=50, verbose_name='Climat')),
                ('statut', models.CharField(choices=[('preparation', 'En préparation'), ('prete', 'Prête'), ('en_cours', 'En cours de voyage'), ('terminee', 'Terminée')], default='preparation', max_length=20, verbose_name='Statut')),
                ('liste_articles_supplementaires', models.TextField(blank=True, help_text='Articles non-vêtements: trousse de toilette, médicaments, chargeurs, etc.', verbose_name='Autres articles')),
                ('notes', models.TextField(blank=True, help_text='Activités prévues, contraintes, rappels...', verbose_name='Notes')),
                ('checklist_faite', models.BooleanField(default=False, verbose_name='Checklist complétée')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('tenues', models.ManyToManyField(blank=True, related_name='valises', to='vetements.tenue', verbose_name='Tenues prévues')),
                ('vetements', models.ManyToManyField(related_name='valises', to='vetements.vetement', verbose_name='Vêtements emportés')),
            ],
            options={
                'verbose_name': 'Valise',
                'verbose_name_plural': 'Valises',
                'ordering': ['-date_depart'],
            },
        ),
    ]
