# Generated by Django 5.2.7 on 2025-10-09 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetements', '0003_valise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenue',
            name='proprietaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tenues', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
        migrations.AddField(
            model_name='valise',
            name='proprietaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='valises', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
        migrations.AddField(
            model_name='vetement',
            name='proprietaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vetements', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet')),
                ('contenu', models.TextField(verbose_name='Message')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('archive_expediteur', models.BooleanField(default=False, verbose_name="Archivé par l'expéditeur")),
                ('archive_destinataire', models.BooleanField(default=False, verbose_name='Archivé par le destinataire')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('en_reponse_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses', to='vetements.message', verbose_name='En réponse à')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
