# Generated by Django 5.2.7 on 2025-10-10 13:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetements', '0004_tenue_proprietaire_valise_proprietaire_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnonceVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix de vente (€)')),
                ('description_vente', models.TextField(blank=True, help_text="Informations supplémentaires pour l'acheteur", verbose_name='Description pour la vente')),
                ('statut', models.CharField(choices=[('en_vente', 'En vente'), ('reservee', 'Réservée'), ('vendue', 'Vendue'), ('retiree', 'Retirée')], default='en_vente', max_length=20, verbose_name='Statut')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('date_vente', models.DateTimeField(blank=True, null=True, verbose_name='Date de vente')),
                ('negociable', models.BooleanField(default=True, verbose_name='Prix négociable')),
                ('livraison_possible', models.BooleanField(default=False, verbose_name='Livraison possible')),
                ('acheteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats', to=settings.AUTH_USER_MODEL, verbose_name='Acheteur')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces_vente', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur')),
                ('vetement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annonce_vente', to='vetements.vetement', verbose_name='Vêtement')),
            ],
            options={
                'verbose_name': 'Annonce de vente',
                'verbose_name_plural': 'Annonces de vente',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Amitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_amitie_envoyees', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_amitie_recues', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Amitié',
                'verbose_name_plural': 'Amitiés',
                'ordering': ['-date_demande'],
                'unique_together': {('demandeur', 'destinataire')},
            },
        ),
    ]
