# Generated by Django 4.2.25 on 2025-10-10 19:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vetements', '0005_annoncevente_amitie'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_site', models.CharField(default='Ma Garde-Robe', max_length=200, verbose_name='Nom du site')),
                ('description_site', models.TextField(blank=True, verbose_name='Description du site')),
                ('email_admin', models.EmailField(blank=True, max_length=254, verbose_name='Email administrateur')),
                ('inscription_ouverte', models.BooleanField(default=True, verbose_name='Inscription ouverte')),
                ('validation_inscription', models.BooleanField(default=False, verbose_name='Validation manuelle des inscriptions')),
                ('messages_actifs', models.BooleanField(default=True, verbose_name='Système de messages activé')),
                ('annonces_actives', models.BooleanField(default=True, verbose_name="Système d'annonces activé")),
                ('amitie_active', models.BooleanField(default=True, verbose_name="Système d'amitié activé")),
                ('max_vetements_par_user', models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max vêtements par utilisateur')),
                ('max_tenues_par_user', models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max tenues par utilisateur')),
                ('max_valises_par_user', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max valises par utilisateur')),
                ('taille_max_image', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Taille max image (MB)')),
                ('moderation_active', models.BooleanField(default=False, verbose_name='Modération activée')),
                ('moderation_messages', models.BooleanField(default=False, verbose_name='Modérer les messages')),
                ('moderation_annonces', models.BooleanField(default=False, verbose_name='Modérer les annonces')),
                ('mode_maintenance', models.BooleanField(default=False, verbose_name='Mode maintenance')),
                ('message_maintenance', models.TextField(blank=True, verbose_name='Message de maintenance')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
        migrations.CreateModel(
            name='RapportModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contenu', models.CharField(choices=[('message', 'Message'), ('annonce', 'Annonce de vente'), ('vetement', 'Vêtement'), ('tenue', 'Tenue'), ('utilisateur', 'Utilisateur')], max_length=20, verbose_name='Type de contenu')),
                ('objet_id', models.IntegerField(verbose_name="ID de l'objet signalé")),
                ('motif', models.TextField(verbose_name='Motif du signalement')),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('date_rapport', models.DateTimeField(auto_now_add=True, verbose_name='Date du rapport')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de traitement'), ('resolu', 'Résolu'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('action_prise', models.CharField(choices=[('aucune', 'Aucune action'), ('avertissement', 'Avertissement'), ('suppression', 'Suppression du contenu'), ('suspension', 'Suspension temporaire'), ('bannissement', 'Bannissement permanent')], default='aucune', max_length=20, verbose_name='Action prise')),
                ('commentaire_moderateur', models.TextField(blank=True, verbose_name='Commentaire du modérateur')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('moderateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderations_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Modérateur')),
                ('rapporteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_envoyes', to=settings.AUTH_USER_MODEL, verbose_name='Rapporteur')),
                ('utilisateur_concerne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_recus', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur concerné')),
            ],
            options={
                'verbose_name': 'Rapport de modération',
                'verbose_name_plural': 'Rapports de modération',
                'ordering': ['-date_rapport'],
            },
        ),
        migrations.CreateModel(
            name='ActionModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('avertissement', 'Avertissement'), ('suppression_contenu', 'Suppression de contenu'), ('suspension', 'Suspension temporaire'), ('bannissement', 'Bannissement permanent'), ('levee_sanction', 'Levée de sanction')], max_length=30, verbose_name="Type d'action")),
                ('motif', models.TextField(verbose_name='Motif')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin (pour suspensions)')),
                ('moderateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Modérateur')),
                ('rapport_lie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vetements.rapportmoderation', verbose_name='Rapport lié')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_moderation', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Action de modération',
                'verbose_name_plural': 'Actions de modération',
                'ordering': ['-date_action'],
            },
        ),
    ]
