# Generated by Django 4.2.25 on 2025-10-10 19:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vetements', '0006_parametressite_rapportmoderation_actionmoderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_final', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix final (€)')),
                ('prix_initial', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix initial (€)')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours de négociation'), ('acceptee', 'Acceptée - En attente de finalisation'), ('finalisee', 'Finalisée'), ('annulee', 'Annulée')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('avec_livraison', models.BooleanField(default=False, verbose_name='Avec livraison')),
                ('adresse_livraison', models.TextField(blank=True, verbose_name='Adresse de livraison')),
                ('notes_vendeur', models.TextField(blank=True, verbose_name='Notes du vendeur')),
                ('notes_acheteur', models.TextField(blank=True, verbose_name="Notes de l'acheteur")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_acceptation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'acceptation")),
                ('date_finalisation', models.DateTimeField(blank=True, null=True, verbose_name='Date de finalisation')),
                ('date_annulation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'annulation")),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Acheteur')),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='vetements.annoncevente', verbose_name='Annonce')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationVendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_globale', models.IntegerField(choices=[(1, '⭐ - Très insatisfait'), (2, '⭐⭐ - Insatisfait'), (3, '⭐⭐⭐ - Correct'), (4, '⭐⭐⭐⭐ - Satisfait'), (5, '⭐⭐⭐⭐⭐ - Très satisfait')], verbose_name='Note globale')),
                ('note_communication', models.IntegerField(choices=[(1, '⭐ - Très insatisfait'), (2, '⭐⭐ - Insatisfait'), (3, '⭐⭐⭐ - Correct'), (4, '⭐⭐⭐⭐ - Satisfait'), (5, '⭐⭐⭐⭐⭐ - Très satisfait')], verbose_name='Communication')),
                ('note_description', models.IntegerField(choices=[(1, '⭐ - Très insatisfait'), (2, '⭐⭐ - Insatisfait'), (3, '⭐⭐⭐ - Correct'), (4, '⭐⭐⭐⭐ - Satisfait'), (5, '⭐⭐⭐⭐⭐ - Très satisfait')], verbose_name='Conformité à la description')),
                ('note_rapidite', models.IntegerField(choices=[(1, '⭐ - Très insatisfait'), (2, '⭐⭐ - Insatisfait'), (3, '⭐⭐⭐ - Correct'), (4, '⭐⭐⭐⭐ - Satisfait'), (5, '⭐⭐⭐⭐⭐ - Très satisfait')], verbose_name='Rapidité')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('recommande', models.BooleanField(default=True, verbose_name='Je recommande ce vendeur')),
                ('date_evaluation', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'évaluation")),
                ('evaluateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_donnees', to=settings.AUTH_USER_MODEL, verbose_name='Évaluateur')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='vetements.transactionvente', verbose_name='Transaction')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_recues', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur évalué')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['-date_evaluation'],
            },
        ),
        migrations.CreateModel(
            name='FavoriAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout aux favoris")),
                ('notification_changement_prix', models.BooleanField(default=True, verbose_name='Notifier en cas de changement de prix')),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='vetements.annoncevente', verbose_name='Annonce')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces_favorites', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'ordering': ['-date_ajout'],
                'unique_together': {('utilisateur', 'annonce')},
            },
        ),
    ]
