# Generated by Django 4.2.25 on 2025-10-10 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetements', '0007_transactionvente_evaluationvendeur_favoriannonce'),
    ]

    operations = [
    ]
