# Generated by Django 4.2.25 on 2025-10-11 05:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vetements', '0008_nouveaux_modeles'),
    ]

    operations = [
        migrations.AddField(
            model_name='valise',
            name='poids_estime',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculé automatiquement', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Poids estimé (kg)'),
        ),
        migrations.AddField(
            model_name='valise',
            name='poids_max',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Poids maximum autorisé (kg)'),
        ),
        migrations.AlterField(
            model_name='valise',
            name='vetements',
            field=models.ManyToManyField(blank=True, related_name='valises_old', to='vetements.vetement', verbose_name='Vêtements emportés (ancien système)'),
        ),
        migrations.CreateModel(
            name='ItemValise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emballe', models.BooleanField(default=False, verbose_name='Emballé')),
                ('categorie_valise', models.CharField(choices=[('vetements', 'Vêtements'), ('chaussures', 'Chaussures'), ('sous_vetements', 'Sous-vêtements'), ('accessoires', 'Accessoires'), ('toilette', 'Toilette'), ('electronique', 'Électronique'), ('documents', 'Documents'), ('sante', 'Santé'), ('autre', 'Autre')], default='vetements', max_length=20, verbose_name='Catégorie dans la valise')),
                ('poids_estime', models.IntegerField(default=200, help_text="Poids moyen de l'article", validators=[django.core.validators.MinValueValidator(0)], verbose_name='Poids estimé (g)')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
                ('note', models.CharField(blank=True, help_text='Ex: À laver avant de partir, Fragile, etc.', max_length=200, verbose_name='Note')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le')),
                ('valise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vetements.valise', verbose_name='Valise')),
                ('vetement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vetements.vetement', verbose_name='Vêtement')),
            ],
            options={
                'verbose_name': 'Item de valise',
                'verbose_name_plural': 'Items de valise',
                'ordering': ['categorie_valise', 'ordre', 'date_ajout'],
                'unique_together': {('valise', 'vetement')},
            },
        ),
    ]
