# Generated by Django 4.2.25 on 2025-10-11 11:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vetements', '0009_valise_improved_checklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementTenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Ex: Réunion client, Dîner restaurant', max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type_evenement', models.CharField(choices=[('travail', 'Travail'), ('reunion', 'Réunion'), ('sortie', 'Sortie'), ('rendez_vous', 'Rendez-vous'), ('ceremonie', 'Cérémonie'), ('sport', 'Sport'), ('voyage', 'Voyage'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name="Type d'événement")),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_debut', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('toute_journee', models.BooleanField(default=False, verbose_name='Événement toute la journée')),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('rappel', models.BooleanField(default=False, verbose_name='Activer un rappel')),
                ('rappel_minutes_avant', models.IntegerField(default=60, help_text="Nombre de minutes avant l'événement", validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rappel (minutes avant)')),
                ('meteo_prevue', models.CharField(blank=True, help_text='Ex: Ensoleillé, Pluvieux', max_length=100, verbose_name='Météo prévue')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
                ('tenue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='vetements.tenue', verbose_name='Tenue prévue')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['date', 'heure_debut'],
            },
        ),
    ]
